#!/bin/bash
#
#kuu nr järgi aastaaja väljastamine
echo -e "Sisesta kuu number \c"
read kuu

if [ $kuu -ge 1 -a $kuu -le 2 -o $kuu -eq 12 ]
then 
	echo "praegu on talv"
elif [ $kuu -ge 3 -a $kuu -le 5 ]
then
	echo "praegu on kevad"
elif [ $kuu -ge 6 -a $kuu -le 8 ]
then
	echo "praegu on suvi"
elif [ $kuu -ge 9 -a $kuu -le 11 ]
then 
	echo "praegu on sügis"
fi
