#!/bin/bash
#
#

echo -n "Sisesta aja väärtus: "
read aeg
if [ $aeg -ge 6 -a $aeg -lt 12 ]; then
	echo "tere hommikust"
elif [ $aeg -ge 12 -a $aeg -lt 18 ]; then
	echo "tere päevast"
elif [ $aeg -ge 18 -a $aeg -lt 22 ]; then
	echo "tere õhtust"
elif [ $aeg -ge 22 -a $aeg -le 24 -o $aeg -ge 0 -a $aeg -lt 6 ]; then
	echo "head ööd"
else
	echo "sisestasite vale arvu"

fi
