#!/bin/bash
#
#
echo  -n "sisesta ridade arv: "
read a				#sisestab  a ridade arvuna
echo  -n "sisesta tärnide arv reas: "
read b				#sisestab b märkide arvuna
for (( i=1; i <= a; i++)) # arvutab ridade arv
do

	for (( j = 1 ; j <= b; j++)) # arvutab märkide arvu reas
	do
	if [ $i -ge $j ]; then
	echo -n "* "
	else 
	echo -n " "
	fi
	done
echo ""   #tühi rida
done
