#!/bin/bash
#
#
echo  -n "sisesta ridade arv: "
read a				#sisestab  a ridade arvuna
for (( i=$a; i>=1; i--)) # arvutab ridade arv
do

	for(( j=1; j<=$a; j++)) # arvutab märkide arvu reas
	do
	if [ $i -ge $j ]; then
	echo -n "* "
	else
	echo -n " "
	fi
	done
echo ""   #tühi rida
done
